name: Render Quarto Document

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t quarto-render:latest .

      # Step to run the Docker image and execute commands inside it
      - name: Run Quarto Render in Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -w /workspace \
            -e "GOOGLE_SHEET_CREDENTIALS=${{ secrets.GOOGLE_SHEET_CREDENTIALS }}" \
            quarto-render:latest \
            bash -c "
              echo \"$GOOGLE_SHEET_CREDENTIALS\" > /tmp/service-account.json && \
              R -e 'library(googlesheets4); gs4_auth(path = \"/tmp/service-account.json\")' && \
              quarto render deviant_art_deployment.qmd --to html
            "
