name: Render Quarto Document

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC; adjust as needed
  workflow_dispatch: # Allows for manual triggering of the action

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies (including compilers)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gfortran libcurl4-openssl-dev libssl-dev libxml2-dev

        
      - name: Install renv and restore environment
        run: |
          R -e "install.packages('renv')"   # Install renv
          R -e "renv::restore()"             # Restore the environment from renv.lock

      - name: Render Quarto Document
        run: quarto render deviant_art_deployment.qmd --to html

      - name: Commit and push changes
        run: |
          git config --local user.email "kevin.vervier04@gmail.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Automated render of Quarto document"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
